version: "3"

networks:
  net:
    driver: bridge

services:
  ros-gazebo:
    build: ../third_party/gazebo/smart_car/
    deploy:
      resources:
        limits:
          cpus: '2'
    ports:
      - "6080:80"
    privileged: false
    networks:
      - net

  godot:
    build: ../third_party/godot/
    ports:
      - "6081:80"
      - "9050:9050"
    privileged: true
    networks:
      - net

  feagi:
    build: ./
    ports:
      - "8001:8000"
    environment:
      - CONTAINERIZED=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ../src/evo/static_genome.py:/opt/source-code/feagi/src/evo/static_genome.py
      - ../src/feagi_configuration.ini:/opt/source-code/feagi/src/feagi_configuration.ini
    networks:
      - net
