version: "3"

services:
  feagi:
    build:
      context: ./
      dockerfile: ./Dockerfile.private
      ssh:
        - default

  gui:
    build:
      context: ../src/gui/
      dockerfile: ./Dockerfile.private
      ssh:
        - default
