version: "3"

networks:
  net:
    driver: bridge

services:
  ros-gazebo:
    build: ../third_party/gazebo/smart_car/
    deploy:
      resources:
        limits:
          cpus: '2'
    ports:
      - "6080:80"
    privileged: false
    networks:
      - net

  godot:
    build: ../third_party/godot/container/
    ports:
      - "6081:80"
      - "20002:20002/udp"
      - "20001:20001/udp"
    privileged: true
    networks:
      - net

  feagi:
    build: ./
    environment:
      - CONTAINERIZED=true
      - PYTHONUNBUFFERED=1

    volumes:
      - ../../smart-car/genome/proximity_test_genome.py:/opt/source-code/feagi/src/evo/static_genome.py
      - ../src/feagi_configuration.ini:/opt/source-code/feagi/src/feagi_configuration.ini
      - ../src/evo/synapse.py:/opt/source-code/feagi/src/evo/synapse.py
    networks:
      - net

volumes:
  grafana_data:
  influxdb_data:
