version: "3"

networks:
  net:
    driver: bridge

services:

  godot:
    build: ../third_party/godot/
    ports:
      - "6081:80"
      - "9050:9050"
    privileged: true
    networks:
      - net
      
  ros-gazebo:
    build: ../third_party/elecfreaks
    privileged: true
    network_mode: host
    devices:
     - "/dev/hci0:/dev/hci0"

  feagi:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - CONTAINERIZED=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ../src/evo/static_genome.py:/opt/source-code/feagi/src/evo/static_genome.py
      - ../src/feagi_configuration.ini:/opt/source-code/feagi/src/feagi_configuration.ini
    networks:
      - net
