name: nrs-feagi(main) -> GAR
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'generate_version.sh'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the required branch
      uses: actions/checkout@v2
      with:
        repository: Neuraville/nrs-feagi
        ref: main

    - name: Push to GCR GitHub Action
      uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
        gcloud_service_key: ${{secrets.NRS_GAR_PUSH_TOKEN}}
        project_id: nrs-core
        registry: us-docker.pkg.dev
        image_name: nrs-feagi-us/feagi
        image_tag: $GITHUB_SHA
        dockerfile: ./docker/Dockerfile
        build_args: REPO=https://${{ secrets.GITHUB_TOKEN }}@github.com/Neuraville/nrs-feagi.git,BRANCH=main
